language: python

python:
  - '3.3'

env:
  global:
    - secure: XE4pnVaOO4//KxlJVZusll7cBkTfOTkVqiHJfv45+e1RtSHa65YxGUhuP+dWC06WboNEhcn/GJ7Y9iEprITbz1nmQsCCIQCRH6jCspyYjF3BgfpXdrPPoIL6CbaexEdYS3PhFlSI4jAfAq6QyJ17/6jSePtcJ0p8WKcXeqvAPhw=

install:
  - pip install -q Sphinx==1.2.2

script:
  - sphinx-build -nW -b html -d doc/doctrees doc doc/html

after_script:
  - ls -laR
  - pwd

