language: python

python:
  - '3.3'

env:
  global:
    - secure: XE4pnVaOO4//KxlJVZusll7cBkTfOTkVqiHJfv45+e1RtSHa65YxGUhuP+dWC06WboNEhcn/GJ7Y9iEprITbz1nmQsCCIQCRH6jCspyYjF3BgfpXdrPPoIL6CbaexEdYS3PhFlSI4jAfAq6QyJ17/6jSePtcJ0p8WKcXeqvAPhw=

install:
  - pip install -q Sphinx==1.2.2

script:
  - sphinx-build -nW -b html -d doc/doctrees doc doc/html

after_script:
  - ls -laR
  - git config --global user.name "sniksnp"
  - git config --global user.email "sniksnp@gmail.com"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git status
  - git branch gh-pages master
  - git checkout gh-pages
  - git add doc/html
  - git commit -m "Automatic commit from Travis"
  - git remote -v
  - git remote set-url origin https://sniksnp:${GH_TOKEN}@github.com/sniksnp/sphinx-helloworld.git
  - git remote -v
  - git push origin gh-pages
